import type { Concept, DomainRequirement } from "./terminologia/types";

/**
 * Aspectos clínicos avaliados pelo PANDA93.
 * Demais domínios da terminologia ficam fora do cálculo.
 */
export const ACTIVE_DOMAIN_ORDER = [
  "qp", // QD
  "hma", // HPMA
  "ap",
  "af",
  "muc",
  "alg",
  "ef",
  "rex",
  "hd",
  "cd",
] as const;

export type ActiveDomain = (typeof ACTIVE_DOMAIN_ORDER)[number];

export const ACTIVE_DOMAIN_LABELS: Record<ActiveDomain, string> = {
  qp: "QD",
  hma: "HPMA",
  ap: "AP",
  af: "AF",
  muc: "MUC",
  alg: "ALERGIA",
  ef: "EF",
  rex: "Resultado de exames",
  hd: "HD",
  cd: "CD",
};

/** Pesos para média ponderada do PANDA93 */
export const ACTIVE_DOMAIN_WEIGHTS: Record<ActiveDomain, number> = {
  qp: 3,
  hma: 5,
  ap: 3,
  af: 1,
  muc: 4,
  alg: 4,
  ef: 5,
  rex: 3,
  hd: 4,
  cd: 4,
};

export const ACTIVE_DOMAIN_REQUIREMENTS: DomainRequirement[] = [
  { d: "qp", req: ["QP001", "QP002"], w: 3 },
  { d: "hma", req: ["HMA001", "HMA002", "HMA003", "HMA004", "HMA014"], w: 5 },
  { d: "ap", req: ["AP001"], w: 3 },
  { d: "af", req: ["AF002"], w: 1 },
  { d: "muc", req: ["MUC001", "MUC002", "MUC004"], w: 4 },
  { d: "alg", req: ["ALG001|ALG002", "ALG003", "ALG004"], w: 4 },
  {
    d: "ef",
    req: ["EF001", "EF002", "EF005", "EF006", "EF007", "EF008", "EF009"],
    w: 5,
  },
  { d: "rex", req: ["REX001", "REX002"], w: 3 },
  { d: "hd", req: ["HD001"], w: 4 },
  { d: "cd", req: ["CD001", "CD002"], w: 4 },
];

export const EXTRA_CONCEPTS: Concept[] = [
  {
    i: "DOC016",
    d: "doc",
    c: "resultado_exames",
    t: ["resultado de exames", "exames complementares", "exames laboratoriais"],
    q: "doc",
    e: 2,
    p: 4,
    r: 2,
    s: 1,
  },
  {
    i: "DOC017",
    d: "doc",
    c: "hipotese_diagnostica",
    t: ["hipótese diagnóstica", "hipotese diagnostica", "hd:", "impressão diagnóstica"],
    q: "doc",
    e: 3,
    p: 5,
    r: 2,
    s: 2,
  },
  {
    i: "DOC018",
    d: "doc",
    c: "conduta",
    t: ["conduta", "cd:", "plano terapêutico", "plano terapeutico"],
    q: "doc",
    e: 3,
    p: 5,
    r: 2,
    s: 2,
  },
  {
    i: "REX001",
    d: "rex",
    c: "exames_mencionados",
    t: [
      "exame",
      "exames",
      "hemograma",
      "pcr",
      "creatinina",
      "ureia",
      "glicemia",
      "ecg",
      "eletrocardiograma",
      "raio-x",
      "radiografia",
      "tomografia",
      "ressonancia",
      "ultrassom",
      "ultrassonografia",
      "gasometria",
      "troponina",
      "d-dimero",
      "cultura",
    ],
    q: "lab",
    e: 2,
    p: 4,
    r: 2,
    s: 1,
    v: "lst",
  },
  {
    i: "REX002",
    d: "rex",
    c: "resultado_ou_pendencia",
    t: [
      "resultado",
      "alterado",
      "dentro da normalidade",
      "pendente",
      "aguardando",
      "sem exames",
      "não realizados",
      "nao realizados",
      "exames disponíveis",
      "exames disponiveis",
    ],
    q: "lab",
    e: 2,
    p: 4,
    r: 2,
    s: 1,
    v: "txt",
  },
  {
    i: "HD001",
    d: "hd",
    c: "hipotese_diagnostica",
    t: [
      "hipótese diagnóstica",
      "hipotese diagnostica",
      "hd:",
      "hd ",
      "diagnósticos",
      "diagnosticos",
      "impressão diagnóstica",
      "impressao diagnostica",
      "sugestivo de",
      "compatível com",
      "compativel com",
    ],
    q: "diag",
    e: 3,
    p: 5,
    r: 2,
    s: 2,
    v: "lst",
  },
  {
    i: "CD001",
    d: "cd",
    c: "conduta_definida",
    t: [
      "conduta",
      "cd:",
      "cd ",
      "prescrevo",
      "prescrito",
      "solicito",
      "solicitado",
      "internação",
      "internacao",
      "alta",
      "orientação",
      "orientacao",
      "plano",
    ],
    q: "plan",
    e: 3,
    p: 5,
    r: 2,
    s: 2,
    v: "txt",
  },
  {
    i: "CD002",
    d: "cd",
    c: "acao_seguinte",
    t: [
      "retorno",
      "reavaliação",
      "reavaliacao",
      "acompanhamento",
      "encaminhamento",
      "observação",
      "observacao",
      "medicação",
      "medicacao",
      "analgesia",
      "hidratação",
      "hidratacao",
    ],
    q: "plan",
    e: 2,
    p: 4,
    r: 2,
    s: 1,
    v: "txt",
  },
];

export const EXTRA_DOC_BY_DOMAIN: Record<string, string> = {
  rex: "DOC016",
  hd: "DOC017",
  cd: "DOC018",
};
