import type { AnamnesisTopic } from "./types";

export const H1_PROMPT_ID = "H1";

export const H1_TOPICS: AnamnesisTopic[] = [
  {
    id: "identificacao",
    label: "Identificação",
    weight: 1,
    patterns: [
      "identifica",
      "nome",
      "idade",
      "anos",
      "sexo",
      "genero",
      "raça",
      "raca",
      "estado civil",
      "natural de",
      "procedente",
      "paciente do sexo",
    ],
    essentialItems: [
      {
        id: "idade",
        label: "Idade",
        patterns: ["idade", "anos", "ano de idade"],
      },
      {
        id: "sexo",
        label: "Sexo/gênero",
        patterns: ["sexo", "genero", "masculino", "feminino", "homem", "mulher"],
      },
      {
        id: "origem",
        label: "Procedência/naturalidade",
        patterns: ["procedente", "natural", "reside", "morador", "cidade"],
      },
    ],
    redFlagPatterns: [],
  },
  {
    id: "qp_qd",
    label: "QP/QD",
    weight: 2,
    patterns: [
      "queixa principal",
      "qp",
      "qd",
      "queixa",
      "procura",
      "motivo da consulta",
      "motivo do atendimento",
    ],
    essentialItems: [
      {
        id: "queixa",
        label: "Queixa principal explícita",
        patterns: ["queixa", "dor", "febre", "dispneia", "tosse", "cefaleia", "nause", "vomit", "sangue", "edema"],
      },
      {
        id: "duracao_qd",
        label: "Duração/tempo da queixa",
        patterns: ["há", "desde", "dias", "semanas", "meses", "horas", "inicio", "início"],
      },
    ],
    redFlagPatterns: ["síncope", "sincope", "dor torácica", "hemoptise", "sangramento", "perda de peso"],
  },
  {
    id: "hma",
    label: "HMA/HPMA",
    weight: 5,
    patterns: [
      "hma",
      "hpma",
      "historia da molestia",
      "história da moléstia",
      "historia da doenca",
      "história da doença",
      "historia atual",
      "evolucao",
      "evolução",
    ],
    essentialItems: [
      {
        id: "inicio",
        label: "Início dos sintomas",
        patterns: ["inicio", "início", "começou", "comecou", "desde", "há", "ha "],
      },
      {
        id: "caracteristicas",
        label: "Características do sintoma principal",
        patterns: ["caracter", "tipo", "qualidade", "localiza", "intensidade", "escala", "eva"],
      },
      {
        id: "cronologia",
        label: "Cronologia/evolução",
        patterns: ["evolu", "piorou", "melhorou", "progress", "cronolog", "depois", "em seguida"],
      },
      {
        id: "fatores",
        label: "Fatores de melhora/piora",
        patterns: ["melhora", "piora", "alivia", "aggrava", "relacionado", "ao esforço", "ao repouso"],
      },
      {
        id: "sintomas_associados",
        label: "Sintomas associados",
        patterns: ["associad", "acompanhad", "nega", "sem outros", "além disso", "tambem", "também"],
      },
      {
        id: "tratamentos_previos",
        label: "Condutas/tratamentos prévios",
        patterns: ["usou", "medica", "procurou", "atendido", "internad", "automedica"],
      },
    ],
    redFlagPatterns: [
      "sinal de alerta",
      "red flag",
      "dor torácica",
      "dor toracica",
      "dispneia",
      "síncope",
      "sincope",
      "deficit neurolog",
      "déficit neurol",
      "sangramento",
      "febre alta",
      "perda de peso",
      "sudorese noturna",
    ],
  },
  {
    id: "is",
    label: "IS",
    weight: 2,
    patterns: [
      "interrogatorio sistematico",
      "interrogatório sistemático",
      "revisao de sistemas",
      "revisão de sistemas",
      "is:",
      "\nis\n",
    ],
    essentialItems: [
      {
        id: "sistemas",
        label: "Revisão de sistemas pertinente",
        patterns: [
          "cardiovascular",
          "respirator",
          "gastro",
          "neurolog",
          "urin",
          "nega outros",
          "sem queixas",
          "sistemas",
        ],
      },
    ],
    redFlagPatterns: ["dispneia", "dor torácica", "sangue", "síncope", "sincope", "perda de peso"],
  },
  {
    id: "ap",
    label: "AP",
    weight: 3,
    patterns: [
      "antecedentes pessoais",
      "antecedentes patologicos",
      "antecedentes patológicos",
      "comorbidades",
      "historico patologico",
      "ap:",
    ],
    essentialItems: [
      {
        id: "doencas",
        label: "Doenças/comorbidades",
        patterns: [
          "hipertens",
          "diabetes",
          "asma",
          "dpoc",
          "cardiopat",
          "renal",
          "tireoid",
          "nega antecedentes",
          "sem comorbidades",
          "hígid",
          "higid",
        ],
      },
      {
        id: "internacoes",
        label: "Internações prévias",
        patterns: ["internac", "hospitaliz", "nega internações", "nega internacoes", "sem internações"],
      },
    ],
    redFlagPatterns: ["descompens", "insuficiencia", "insuficiência"],
  },
  {
    id: "cirurgicos",
    label: "Antecedentes cirúrgicos",
    weight: 2,
    patterns: [
      "antecedentes cirurgicos",
      "antecedentes cirúrgicos",
      "cirurgia",
      "operado",
      "procedimento cirurgico",
    ],
    essentialItems: [
      {
        id: "cirurgias",
        label: "Cirurgias prévias (ou negação)",
        patterns: [
          "cirurgia",
          "operado",
          "apendic",
          "cesarea",
          "cesárea",
          "hernia",
          "hérnia",
          "nega cirurg",
          "sem cirurg",
        ],
      },
    ],
    redFlagPatterns: [],
  },
  {
    id: "muc",
    label: "MUC",
    weight: 4,
    patterns: [
      "medicamentos em uso",
      "medicacoes em uso",
      "medicações em uso",
      "muc",
      "em uso de",
      "faz uso de",
      "medicação contínua",
      "medicacao continua",
    ],
    essentialItems: [
      {
        id: "nome",
        label: "Nome do medicamento",
        patterns: [
          "mg",
          "comprimido",
          "capsula",
          "cápsula",
          "losartana",
          "metformina",
          "omeprazol",
          "aas",
          "enalapril",
          "insulina",
          "nega medicamentos",
          "sem medicação",
          "sem medicacao",
          "não usa medicação",
          "nao usa medicacao",
        ],
      },
      {
        id: "dose",
        label: "Dose",
        patterns: ["mg", "mcg", "g ", "ui", "ml", "dose"],
      },
      {
        id: "frequencia",
        label: "Frequência",
        patterns: ["1x", "2x", "3x", "vez", "ao dia", "/dia", "12/12", "8/8", "sos", "se necessário"],
      },
    ],
    redFlagPatterns: ["anticoagulant", "insulina", "imunossupress", "corticoide"],
  },
  {
    id: "alergias",
    label: "Alergias",
    weight: 4,
    patterns: ["alerg", "hipersensibil", "reação a", "reacao a", "anafilax"],
    essentialItems: [
      {
        id: "status",
        label: "Presença ou negação de alergias",
        patterns: ["alerg", "nega alerg", "sem alerg", "não possui alerg", "nao possui alerg"],
      },
      {
        id: "agente",
        label: "Agente e reação (se positiva)",
        patterns: [
          "penicilina",
          "dipirona",
          "aas",
          "latex",
          "látex",
          "urticaria",
          "urticária",
          "choque",
          "edema de glote",
          "nega alerg",
          "sem alerg",
        ],
        notApplicablePatterns: ["nega alerg", "sem alerg", "não possui alerg", "nao possui alerg"],
      },
    ],
    redFlagPatterns: ["anafilax", "edema de glote", "choque anafilatico", "choque anafilático"],
  },
  {
    id: "af",
    label: "AF",
    weight: 1,
    patterns: [
      "antecedentes familiares",
      "historia familiar",
      "história familiar",
      "af:",
      "pai com",
      "mãe com",
      "mae com",
    ],
    essentialItems: [
      {
        id: "familia",
        label: "Antecedentes familiares relevantes (ou negação)",
        patterns: [
          "familiar",
          "pai",
          "mãe",
          "mae",
          "irmão",
          "irmao",
          "diabetes",
          "hipertens",
          "cancer",
          "câncer",
          "nega antecedentes familiares",
          "sem antecedentes familiares",
        ],
      },
    ],
    redFlagPatterns: [],
  },
  {
    id: "habitos",
    label: "Hábitos de vida",
    weight: 2,
    patterns: [
      "habitos",
      "hábitos",
      "tabag",
      "etilism",
      "alcool",
      "álcool",
      "drogas",
      "atividade fisica",
      "atividade física",
    ],
    essentialItems: [
      {
        id: "tabagismo",
        label: "Tabagismo",
        patterns: ["tabag", "cigarro", "fuma", "ex-fumante", "nega tabag", "não fuma", "nao fuma"],
      },
      {
        id: "etilismo",
        label: "Etilismo",
        patterns: ["etil", "alcool", "álcool", "bebe", "nega etil", "não bebe", "nao bebe"],
      },
      {
        id: "outras_substancias",
        label: "Outras substâncias / atividade física",
        patterns: ["droga", "cannabis", "cocaina", "cocaína", "atividade fisica", "atividade física", "sedentar"],
      },
    ],
    redFlagPatterns: ["uso pesado", "abstinencia", "abstinência"],
  },
  {
    id: "ocupacional",
    label: "História ocupacional",
    weight: 1,
    patterns: [
      "ocupacional",
      "profiss",
      "trabalha",
      "ocupação",
      "ocupacao",
      "exposição ocupacional",
      "exposicao ocupacional",
    ],
    essentialItems: [
      {
        id: "ocupacao",
        label: "Ocupação/exposição",
        patterns: [
          "trabalha",
          "profiss",
          "aposentad",
          "desempreg",
          "estudante",
          "exposição",
          "exposicao",
          "ocupação",
          "ocupacao",
        ],
      },
    ],
    redFlagPatterns: ["asbest", "silica", "sílica", "solv ente", "pesticida"],
  },
  {
    id: "gineco",
    label: "História ginecológica e obstétrica",
    weight: 2,
    optionallyApplicable: true,
    contextRequiredPatterns: [
      "feminino",
      "mulher",
      "gestante",
      "menstru",
      "gravidez",
      "gesta",
      "parto",
      "ginec",
      "obstetr",
      "dum",
    ],
    patterns: [
      "ginecolog",
      "obstetr",
      "menstru",
      "dum",
      "gesta",
      "para ",
      "aborto",
      "anticoncepc",
      "gravidez",
    ],
    essentialItems: [
      {
        id: "dum",
        label: "DUM / ciclo",
        patterns: ["dum", "menstru", "ciclo", "amenorre"],
      },
      {
        id: "gesta_para",
        label: "Gesta/Para/Abortos",
        patterns: ["gesta", "para", "aborto", "cesarea", "cesárea", "parto"],
      },
    ],
    redFlagPatterns: ["sangramento vaginal", "ectopica", "ectópica", "pré-eclamps", "pre-eclamps"],
  },
  {
    id: "sexual",
    label: "História sexual",
    weight: 1,
    optionallyApplicable: true,
    patterns: [
      "historia sexual",
      "história sexual",
      "vida sexual",
      "parceiro",
      "dst",
      "ist",
      "preservativo",
      "atividade sexual",
    ],
    essentialItems: [
      {
        id: "atividade",
        label: "Atividade sexual / risco",
        patterns: [
          "sexual",
          "parceiro",
          "preservativo",
          "dst",
          "ist",
          "nega atividade sexual",
          "sem atividade sexual",
        ],
      },
    ],
    redFlagPatterns: ["dst", "ist", "hiv", "sifilis", "sífilis"],
  },
  {
    id: "epidemiologica",
    label: "História epidemiológica",
    weight: 2,
    patterns: [
      "epidemiolog",
      "contato com",
      "viagem",
      "surto",
      "vacina",
      "imuniza",
      "endem",
      "covid",
      "tuberculose",
      "tb ",
    ],
    essentialItems: [
      {
        id: "exposicao",
        label: "Exposição/contatos/viagens",
        patterns: [
          "contato",
          "viagem",
          "vacina",
          "imuniza",
          "covid",
          "tuberculose",
          "nega contato",
          "sem viagens",
        ],
      },
    ],
    redFlagPatterns: ["tuberculose", "febre amarela", "dengue", "covid", "meningite"],
  },
  {
    id: "exame_fisico",
    label: "Exame físico",
    weight: 5,
    patterns: [
      "exame fisico",
      "exame físico",
      "ef:",
      "sinais vitais",
      "pa ",
      "fc ",
      "fr ",
      "tax",
      "spo2",
      "saturação",
      "saturacao",
      "ao exame",
    ],
    essentialItems: [
      {
        id: "sinais_vitais",
        label: "Sinais vitais",
        patterns: [
          "sinais vitais",
          "pa ",
          "mmhg",
          "fc ",
          "bpm",
          "fr ",
          "irpm",
          "tax",
          "°c",
          "spo2",
          "saturação",
          "saturacao",
        ],
      },
      {
        id: "estado_geral",
        label: "Estado geral / aparência",
        patterns: ["estado geral", "bom estado", "regular estado", "mal estado", "lucid", "orientad", "corado", "descorado"],
      },
      {
        id: "exame_dirigido",
        label: "Exame dirigido à queixa",
        patterns: [
          "ausculta",
          "palpa",
          "inspec",
          "abdomen",
          "abdômen",
          "torax",
          "tórax",
          "pulmonar",
          "cardiaco",
          "cardíaco",
          "neurolog",
        ],
      },
    ],
    redFlagPatterns: [
      "hipotens",
      "taquicard",
      "taquipne",
      "febre",
      "hipox",
      "cianose",
      "rebaixamento",
      "sinais de gravidade",
    ],
  },
];

export function classifyCiq(score: number): {
  band: import("./types").CiqBand;
  label: string;
} {
  if (score >= 90) return { band: "excelente", label: "Excelente" };
  if (score >= 75) return { band: "adequado", label: "Adequado" };
  if (score >= 60) return { band: "parcialmente_adequado", label: "Parcialmente adequado" };
  if (score >= 40) return { band: "insuficiente", label: "Insuficiente" };
  return { band: "criticamente_incompleto", label: "Criticamente incompleto" };
}
