export type H2Item = {
  id: string;
  label: string;
  patterns: string[];
  essential: boolean;
};

export type H2Section = {
  id: string;
  label: string;
  items: H2Item[];
};

/**
 * Checklist H2 — Initial Assessment of acute ischemic stroke
 * (presença das informações clinicamente críticas no texto).
 */
export const H2_SECTIONS: H2Section[] = [
  {
    id: "goals",
    label: "Objetivos iniciais",
    items: [
      {
        id: "reperfusion_candidate",
        label: "Elegibilidade para trombólise IV e/ou trombectomia",
        patterns: [
          "trombolise",
          "trombólise",
          "alteplase",
          "tenecteplase",
          "tpa",
          "rtpa",
          "trombectomia",
          "endovascular",
          "reperfusao",
          "reperfusão",
          "janela terapeutica",
          "janela terapêutica",
        ],
        essential: true,
      },
      {
        id: "abc_stability",
        label: "Estabilidade clínica (via aérea, respiração e circulação)",
        patterns: [
          "via aerea",
          "via aérea",
          "respiracao",
          "respiração",
          "circulacao",
          "circulação",
          "abc",
          "estabilidade",
          "sinais vitais",
          "hemodinam",
        ],
        essential: true,
      },
      {
        id: "reversible_causes",
        label: "Condições reversíveis contribuintes",
        patterns: [
          "hipoglicemia",
          "hiperglicemia",
          "reversivel",
          "reversível",
          "causas contribuintes",
          "intoxicacao",
          "intoxicação",
          "convulsao",
          "convulsão",
        ],
        essential: true,
      },
    ],
  },
  {
    id: "time",
    label: "Tempo e triagem",
    items: [
      {
        id: "onset_or_lkw",
        label: "Horário de início ou last known well",
        patterns: [
          "inicio dos sintomas",
          "início dos sintomas",
          "horario",
          "horário",
          "last known well",
          "ultima vez visto bem",
          "última vez visto bem",
          "visto bem",
          "onset",
          "ha horas",
          "há horas",
          "minutos",
        ],
        essential: true,
      },
      {
        id: "witness",
        label: "Testemunha / contato de familiar",
        patterns: [
          "testemunha",
          "familiar",
          "acompanhante",
          "esposa",
          "esposo",
          "filho",
          "filha",
          "paramedico",
          "paramédico",
          "samu",
        ],
        essential: false,
      },
      {
        id: "stroke_scale_prehospital",
        label: "Escala pré-hospitalar (FAST/CPSS/LAPSS) ou suspeita de AVC",
        patterns: [
          "fast",
          "cpss",
          "lapss",
          "suspeita de avc",
          "codigo avc",
          "código avc",
          "stroke code",
          "pre-hospitalar",
          "pré-hospitalar",
        ],
        essential: false,
      },
      {
        id: "lvo_triage",
        label: "Triagem de oclusão de grande vaso (RACE/LAMS/C-STAT)",
        patterns: [
          "race",
          "lams",
          "c-stat",
          "grande vaso",
          "large vessel",
          "oclusao",
          "oclusão",
          "lvo",
        ],
        essential: false,
      },
    ],
  },
  {
    id: "abc",
    label: "Via aérea, respiração e circulação",
    items: [
      {
        id: "vitals",
        label: "Sinais vitais",
        patterns: [
          "sinais vitais",
          "pa ",
          "pressao",
          "pressão",
          "fc ",
          "fr ",
          "bpm",
          "mmhg",
        ],
        essential: true,
      },
      {
        id: "airway",
        label: "Avaliação de via aérea / risco de aspiração",
        patterns: [
          "via aerea",
          "via aérea",
          "aspiracao",
          "aspiração",
          "intubacao",
          "intubação",
          "nivel de consciencia",
          "nível de consciência",
          "glasgow",
          "bulbar",
        ],
        essential: true,
      },
      {
        id: "oxygen",
        label: "Saturação de O₂ / oxigenoterapia se hipóxia",
        patterns: [
          "spo2",
          "saturacao",
          "saturação",
          "oxigenio",
          "oxigênio",
          "o2",
          "hipoxia",
          "hipóxia",
          ">94",
          "maior que 94",
        ],
        essential: true,
      },
    ],
  },
  {
    id: "history_exam",
    label: "História e exame físico",
    items: [
      {
        id: "thrombolysis_contraindications",
        label: "Contraindicações à trombólise",
        patterns: [
          "contraindicacao",
          "contraindicação",
          "anticoagulant",
          "anticoagula",
          "varfarina",
          "inr",
          "sangramento",
          "cirurgia recente",
          "trauma recente",
          "hemorragia",
        ],
        essential: true,
      },
      {
        id: "differential",
        label: "Diagnósticos diferenciais / mímicos de AVC",
        patterns: [
          "diferencial",
          "mimico",
          "mímico",
          "crise convulsiva",
          "epilepsia",
          "migranea",
          "enxaqueca",
          "sincope",
          "síncope",
          "hipoglicemia",
          "intoxicacao",
          "vertigem",
        ],
        essential: true,
      },
      {
        id: "ich_sah_clues",
        label: "Sinais sugestivos de ICH/SAH (cefaleia, vômitos)",
        patterns: [
          "cefaleia",
          "cefaleia intensa",
          "vomito",
          "vômito",
          "hemorragia intracraniana",
          "hemorragia subaracnoidea",
          "hsa",
          "ich",
          "sah",
        ],
        essential: true,
      },
      {
        id: "vascular_cardiac_exam",
        label: "Exame vascular/cardíaco (sopros, pulsos, ausculta)",
        patterns: [
          "sopro",
          "bruit",
          "pulsos",
          "carotida",
          "carótida",
          "ausculta cardiaca",
          "ausculta cardíaca",
          "murmurio",
          "murmúrio",
          "fibrilacao",
          "fibrilação",
        ],
        essential: false,
      },
      {
        id: "skin_trauma_extremities",
        label: "Pele, trauma craniano e extremidades",
        patterns: [
          "petequia",
          "purpura",
          "equimose",
          "trauma",
          "laceracao de lingua",
          "laceração de língua",
          "endocardite",
          "tvp",
          "embolia periferica",
          "embolia periférica",
        ],
        essential: false,
      },
    ],
  },
  {
    id: "neuro",
    label: "Avaliação neurológica",
    items: [
      {
        id: "nihss",
        label: "NIHSS (ou escala neurológica quantificada)",
        patterns: [
          "nihss",
          "nih stroke",
          "escala de avc",
          "escore neurologico",
          "escore neurológico",
        ],
        essential: true,
      },
      {
        id: "focal_signs",
        label: "Sinais focais (face, braço, fala)",
        patterns: [
          "paresia facial",
          "desvio de comissura",
          "hemiparesia",
          "deficit motor",
          "déficit motor",
          "drift",
          "disartria",
          "afasia",
          "fala alterada",
          "hemiplegia",
        ],
        essential: true,
      },
      {
        id: "territory",
        label: "Território vascular / síndrome específica",
        patterns: [
          "territorio",
          "território",
          "acm",
          "aca",
          "acp",
          "vertebrobasilar",
          "circulacao posterior",
          "circulação posterior",
          "capsula interna",
          "cápsula interna",
        ],
        essential: false,
      },
    ],
  },
  {
    id: "immediate_tests",
    label: "Exames imediatos",
    items: [
      {
        id: "ct_or_mri",
        label: "TC sem contraste ou RM de crânio",
        patterns: [
          "tomografia",
          "tc de cranio",
          "tc de crânio",
          "tc sem contraste",
          "ressonancia",
          "ressonância",
          "rm de cranio",
          "rm de crânio",
          "neuroimagem",
        ],
        essential: true,
      },
      {
        id: "glucose",
        label: "Glicemia (capilar/fingerstick)",
        patterns: [
          "glicemia",
          "hgt",
          "dextro",
          "glicose",
          "fingerstick",
          "hemoglicoteste",
        ],
        essential: true,
      },
      {
        id: "spo2_lab",
        label: "Saturação de oxigênio",
        patterns: ["spo2", "saturacao", "saturação", "oximetria"],
        essential: true,
      },
      {
        id: "ecg",
        label: "Eletrocardiograma",
        patterns: ["ecg", "eletrocardiograma", "eletro"],
        essential: true,
      },
      {
        id: "cbc_coag",
        label: "Hemograma e coagulação (plaquetas, TP/INR, TTPa)",
        patterns: [
          "hemograma",
          "plaquetas",
          "inr",
          "tp ",
          "ttpa",
          "coagulograma",
          "tempo de protrombina",
        ],
        essential: true,
      },
      {
        id: "troponin",
        label: "Troponina",
        patterns: ["troponina", "tropo"],
        essential: true,
      },
      {
        id: "cta_perfusion",
        label: "AngioTC/perfusão ou angioRM (se candidato a trombectomia)",
        patterns: [
          "angiotc",
          "angio-tc",
          "angio tc",
          "ctcangiografia",
          "angioressonancia",
          "angiorm",
          "perfusao",
          "perfusão",
          "dwi",
          "pwi",
        ],
        essential: false,
      },
      {
        id: "weight",
        label: "Peso corporal (dose de trombólise)",
        patterns: ["peso", "kg", "quilograma"],
        essential: false,
      },
    ],
  },
  {
    id: "cardiac",
    label: "Avaliação cardíaca",
    items: [
      {
        id: "monitoring_af",
        label: "Monitorização cardíaca / busca de FA",
        patterns: [
          "monitorizacao",
          "monitorização",
          "telemetria",
          "fibrilacao atrial",
          "fibrilação atrial",
          "fa ",
          "flutter",
          "arritmia",
        ],
        essential: true,
      },
      {
        id: "echo",
        label: "Ecocardiograma (quando indicado)",
        patterns: [
          "ecocardiograma",
          "eco tt",
          "eco te",
          "transtoracico",
          "transtorácico",
          "transesofagico",
          "transesofágico",
          "endocardite",
        ],
        essential: false,
      },
    ],
  },
];
